spring:
  application:
    name: event-receiver

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/event_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/event-platform