server:
  port: 8090

spring:

  application:
    name: statistic-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: clickhouse-writer
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring.json.value.default.type: ru.shpg.statisticservice.model.TransactionEvent
#        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    user: default
    password: default

  http:
    client:
      factory: simple

app:
  kafka:
    topic: outbox.transaction