server:
  port: 8090

spring:

  application:
    name: statistic-service

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: clickhouse-writer
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:clickhouse://${DB_HOST:localhost}:${DB_PORT:8123}/event_db
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    user: ${DB_USER:default}
    password: ${DB_PASSWORD:default}

app:
  kafka:
    topic: outbox.transaction