
networks:
  app-network:
    driver: bridge

services:

  event-receiver:
    build:
      context: ..
      dockerfile: services/event-receiver/Dockerfile
    container_name: event-receiver
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres

  # ------------------ POSTGRES ------------------
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c wal_keep_size=512MB
      -c max_connections=200
    ports:
      - "5439:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ------------------ KAFKA (KRaft) ------------------
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - app-network
    environment:
      # Настройки узла KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Позволяет транзакциям работать в кластере из 1 брокера
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Одна реплика для внутренних топиков
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  # ------------------ KAFKA UI ------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9595:8080"
    networks:
      - app-network
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  # ------------------ KAFKA CONNECT + DEBEZIUM ------------------
  kafka-connect:
    image: debezium/connect:2.7.3.Final
    container_name: kafka-connect
    user: "0"
    platform: linux/amd64
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: connect-cluster

      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER_SCHEMAS_ENABLE: false

      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
#    volumes:
#      - ./connectors:/kafka/connect

  connect-init:
    image: curlimages/curl:latest
    container_name: connect-init
    depends_on:
      - kafka-connect
    networks:
      - app-network
    volumes:
      - ./connectors/init-connector.sh:/scripts/init-connector.sh:ro
      - ./connectors/outbox-event-connector.json:/configs/outbox-event-connector.json:ro
    entrypoint: ["/bin/sh", "/scripts/init-connector.sh"]
    environment:
      - CONNECT_URL=http://kafka-connect:8083
      - CONFIG_FILE=/configs/outbox-event-connector.json


  # ------------------ KEYCLOAK ------------------
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0
#    container_name: keycloak
#    command: start-dev
#    environment:
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres:5432/event_db
#      KC_DB_USERNAME: postgres
#      KC_DB_PASSWORD: postgres
#
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - "9191:8080"
#     networks:
#       - app-network
#    depends_on:
#      - postgres

  # ------------------ PROMETHEUS ------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  # ------------------ GRAFANA ------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus

  # ------------------ clickhouse ------------------
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  postgres_data:
  clickhouse_data: