
services:

#   ------------------ event-receiver ------------------
  event-receiver:
    build:
      context: ..
      dockerfile: services/event-receiver/Dockerfile
    container_name: event-receiver
    cap_add:
      - SYS_PTRACE
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      LOKI_URL: http://loki:3100
    depends_on:
      - postgres
      - kafka

#  # ------------------ analytic-service ------------------
  analytic-service:
    build:
      context: ..
      dockerfile: services/analytic-service/Dockerfile
    container_name: analytic-service
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: default
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    depends_on:
      - kafka

  # ------------------ statistic-service ------------------
  statistic-service:
    build:
      context: ..
      dockerfile: services/statistic-service/Dockerfile
    container_name: statistic-service
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: default
      DB_HOST: clickhouse
      DB_PORT: 8123
      DB_USER: default
      DB_PASSWORD: default
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    depends_on:
      - clickhouse
      - kafka

  # ------------------ POSTGRES ------------------
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c wal_keep_size=512MB
      -c max_connections=200
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ------------------ clickhouse ------------------
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # ------------------ KAFKA (KRaft) ------------------
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # Настройки узла KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 12

      # Позволяет транзакциям работать в кластере из 1 брокера
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Одна реплика для внутренних топиков
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ------------------ KAFKA UI ------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9595:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  # ------------------ KAFKA CONNECT + DEBEZIUM ------------------
  kafka-connect:
    image: debezium/connect:2.7.3.Final
    container_name: kafka-connect
    user: "0"
    platform: linux/amd64
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: connect-cluster

      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER_SCHEMAS_ENABLE: false

      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1

  connect-init:
    image: curlimages/curl:latest
    container_name: connect-init
    volumes:
      - ./connectors/init-connector.sh:/scripts/init-connector.sh:ro
      - ./connectors/outbox-event-connector.json:/configs/outbox-event-connector.json:ro
    entrypoint: ["/bin/sh", "/scripts/init-connector.sh"]
    environment:
      CONNECT_URL: http://kafka-connect:8083
      CONFIG_FILE: /configs/outbox-event-connector.json
    depends_on:
      - kafka-connect
      - event-receiver

  # ------------------ PROMETHEUS ------------------
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # ------------------ GRAFANA ------------------
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # Провижининг (настройки)
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # Сами файлы дашбордов
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    depends_on:
      - prometheus

  # -------------------- LOKI --------------------
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  postgres_data:
  clickhouse_data: